project:
  type: website
  output-dir: docs
  resources:
    - CNAME
  render:
    - index.qmd
    - about.qmd
    - projects.qmd
    - blog.qmd
    - posts/*.qmd

website:
  title: "Jon Finger"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
