project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - assets/**
    - design-system/**
    - useless-tools/**
  render:
    - index.qmd
    - about.qmd
    - blog.qmd
    - posts/*.qmd

website:
  title: "Jon Finger"
  favicon: assets/icons/favicon.svg
  search: false
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jae-finger/
        target: _blank
        aria-label: LinkedIn
      - icon: bluesky
        href: https://bsky.app/profile/jonfinger.com
        target: _blank
        aria-label: Bluesky

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-after-body:
      - assets/site-footer.html
